import{ supabase }from'./supabase.js';import{requireBackoffice,setupShell,number,esc}from'./auth.js'
let rows=[];const ctx=await requireBackoffice();if(ctx){setupShell(ctx,'ingredient-categories');await load()}
async function load(){const{data,error}=await supabase.rpc('backoffice_list_ingredient_categories');if(error)return msg(error.message);rows=data||[];render()}
function msg(t=''){document.getElementById('message').textContent=t}
function render(){document.getElementById('table').innerHTML=`<div class="table-wrap"><table><thead><tr><th>ลำดับ</th><th>หมวด</th><th class="num">วัตถุดิบ</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${number(x.display_order,0)}</td><td><strong>${esc(x.name)}</strong></td><td class="num">${number(x.ingredient_count,0)}</td><td>${x.is_active?'<span class="badge ok">ใช้งาน</span>':'<span class="badge">ปิด</span>'}</td><td><button class="small-btn" data-edit="${x.id}">แก้ไข</button></td></tr>`).join('')}</tbody></table></div>`}
function open(r=null){document.getElementById('id').value=r?.id||'';document.getElementById('name').value=r?.name||'';document.getElementById('order').value=r?.display_order??100;document.getElementById('active').checked=r?r.is_active!==false:true;document.getElementById('formMessage').textContent='';document.getElementById('modal').classList.remove('hidden')}
async function save(){const n=document.getElementById('name').value.trim();if(!n)return fmsg('กรุณาระบุชื่อหมวด');const{error}=await supabase.rpc('backoffice_save_ingredient_category',{p_category_id:document.getElementById('id').value||null,p_name:n,p_display_order:Number(document.getElementById('order').value||100),p_is_active:document.getElementById('active').checked});if(error)return fmsg(error.message.includes('CATEGORY_NAME_EXISTS')?'มีชื่อหมวดนี้แล้ว':error.message);document.getElementById('modal').classList.add('hidden');await load()}
function fmsg(t){document.getElementById('formMessage').textContent=t}
document.getElementById('addBtn').onclick=()=>open();document.getElementById('closeBtn').onclick=()=>document.getElementById('modal').classList.add('hidden');document.getElementById('saveBtn').onclick=save;document.getElementById('table').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)open(rows.find(x=>x.id===b.dataset.edit))}
