import { supabase } from './supabase.js'
import { requireBackoffice, setupShell, money, number, esc } from './auth.js'
let rows=[],categories=[]
const ctx=await requireBackoffice()
if(ctx){setupShell(ctx,'ingredients');await Promise.all([loadCategories(),load()])}
async function loadCategories(){const{data,error}=await supabase.rpc('backoffice_list_ingredient_categories');if(error)return show(error.message);categories=data||[];document.getElementById('categoryFilter').innerHTML='<option value="">ทุกหมวด</option>'+categories.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');document.getElementById('ingredientCategory').innerHTML='<option value="">-- ยังไม่ระบุ --</option>'+categories.filter(x=>x.is_active).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
async function load(){const{data,error}=await supabase.rpc('backoffice_list_ingredients_v3');if(error)return show(error.message);rows=data||[];render()}
function show(t=''){document.getElementById('message').textContent=t}
function errText(e){const t=String(e?.message||e||'');if(t.includes('INGREDIENT_NAME_EXISTS'))return'มีวัตถุดิบชื่อนี้อยู่แล้วในสาขานี้';return t||'บันทึกไม่สำเร็จ'}
const freqText=x=>({daily:'รายวัน',weekly:'รายสัปดาห์',monthly:'รายเดือน'})[x]||x
function filtered(){const q=document.getElementById('search').value.trim().toLowerCase(),s=document.getElementById('status').value,c=document.getElementById('categoryFilter').value,f=document.getElementById('frequencyFilter').value;return rows.filter(x=>{const ok=!q||`${x.name} ${x.category_name||''}`.toLowerCase().includes(q);let st=true;if(s==='low')st=x.is_active&&Number(x.current_stock)>0&&Number(x.current_stock)<=Number(x.min_stock);if(s==='out')st=x.is_active&&Number(x.current_stock)<=0;if(s==='inactive')st=!x.is_active;return ok&&st&&(!c||x.category_id===c)&&(!f||x.count_frequency===f)})}
function render(){const a=rows.filter(x=>x.is_active);document.getElementById('totalCount').textContent=number(a.length,0);document.getElementById('lowCount').textContent=number(a.filter(x=>Number(x.current_stock)>0&&Number(x.current_stock)<=Number(x.min_stock)).length,0);document.getElementById('outCount').textContent=number(a.filter(x=>Number(x.current_stock)<=0).length,0);document.getElementById('stockValue').textContent=money(a.reduce((s,x)=>s+Number(x.current_stock||0)*Number(x.cost_per_unit||0),0));const list=filtered();document.getElementById('table').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>วัตถุดิบ</th><th>หมวด</th><th>รอบนับ</th><th>หน่วย</th><th class="num">ต้นทุน/หน่วย</th><th class="num">คงเหลือ</th><th class="num">ขั้นต่ำ</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>${list.map(x=>{const cur=Number(x.current_stock||0),min=Number(x.min_stock||0),badge=!x.is_active?'<span class="badge">ปิด</span>':cur<=0?'<span class="badge out">หมด</span>':cur<=min?'<span class="badge low">ต่ำ</span>':'<span class="badge ok">ปกติ</span>';return`<tr><td><strong>${esc(x.name)}</strong></td><td><span class="category-chip">${esc(x.category_name||'อื่นๆ')}</span></td><td><span class="freq-chip">${freqText(x.count_frequency)}</span></td><td>${esc(x.unit)}</td><td class="num">${money(x.cost_per_unit)}</td><td class="num">${number(x.current_stock)} ${esc(x.unit)}</td><td class="num">${number(x.min_stock)}</td><td>${badge}</td><td><div class="action-row"><button class="small-btn" data-adjust="${x.id}">ปรับ Stock</button><button class="small-btn" data-edit="${x.id}">แก้ไข</button></div></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">ไม่พบวัตถุดิบ</div>'}
function openIngredient(r=null){document.getElementById('ingredientId').value=r?.id||'';document.getElementById('ingredientName').value=r?.name||'';document.getElementById('ingredientUnit').value=r?.unit||'';document.getElementById('ingredientCategory').value=r?.category_id||'';document.getElementById('ingredientFrequency').value=r?.count_frequency||'monthly';document.getElementById('ingredientCost').value=Number(r?.cost_per_unit||0);document.getElementById('ingredientMin').value=Number(r?.min_stock||0);document.getElementById('ingredientActive').checked=r?r.is_active!==false:true;document.getElementById('ingredientModalTitle').textContent=r?'แก้ไขวัตถุดิบ':'เพิ่มวัตถุดิบ';document.getElementById('ingredientFormMessage').textContent='';document.getElementById('ingredientModal').classList.remove('hidden')}
async function saveIngredient(){const name=document.getElementById('ingredientName').value.trim(),unit=document.getElementById('ingredientUnit').value.trim();if(!name||!unit){document.getElementById('ingredientFormMessage').textContent='กรุณาระบุชื่อและหน่วย';return}const{error}=await supabase.rpc('backoffice_save_ingredient_v3',{p_ingredient_id:document.getElementById('ingredientId').value||null,p_name:name,p_unit:unit,p_cost_per_unit:Number(document.getElementById('ingredientCost').value||0),p_min_stock:Number(document.getElementById('ingredientMin').value||0),p_is_active:document.getElementById('ingredientActive').checked,p_category_id:document.getElementById('ingredientCategory').value||null,p_count_frequency:document.getElementById('ingredientFrequency').value});if(error){document.getElementById('ingredientFormMessage').textContent=errText(error);return}document.getElementById('ingredientModal').classList.add('hidden');await load()}
function openAdjust(r){document.getElementById('adjustId').value=r.id;document.getElementById('adjustName').textContent=`${r.name} • คงเหลือ ${number(r.current_stock)} ${r.unit}`;document.getElementById('adjustQty').value='';document.getElementById('adjustCost').value=Number(r.cost_per_unit||0);document.getElementById('adjustNote').value='';document.getElementById('adjustMessage').textContent='';document.getElementById('adjustModal').classList.remove('hidden')}
async function saveAdjust(){const q=Number(document.getElementById('adjustQty').value||0);if(q<=0){document.getElementById('adjustMessage').textContent='จำนวนต้องมากกว่า 0';return}const{error}=await supabase.rpc('backoffice_adjust_stock',{p_ingredient_id:document.getElementById('adjustId').value,p_movement_type:document.getElementById('movementType').value,p_quantity:q,p_unit_cost:Number(document.getElementById('adjustCost').value||0),p_note:document.getElementById('adjustNote').value.trim()||null});if(error){document.getElementById('adjustMessage').textContent=error.message;return}document.getElementById('adjustModal').classList.add('hidden');await load()}
document.getElementById('addBtn').onclick=()=>openIngredient();document.getElementById('refreshBtn').onclick=async()=>{await loadCategories();await load()};['search','categoryFilter','frequencyFilter','status'].forEach(id=>document.getElementById(id).addEventListener(id==='search'?'input':'change',render));document.getElementById('closeIngredientModal').onclick=()=>document.getElementById('ingredientModal').classList.add('hidden');document.getElementById('closeAdjustModal').onclick=()=>document.getElementById('adjustModal').classList.add('hidden');document.getElementById('saveIngredientBtn').onclick=saveIngredient;document.getElementById('saveAdjustBtn').onclick=saveAdjust;document.getElementById('table').onclick=e=>{const ed=e.target.closest('[data-edit]'),ad=e.target.closest('[data-adjust]');if(ed)return openIngredient(rows.find(x=>x.id===ed.dataset.edit));if(ad)return openAdjust(rows.find(x=>x.id===ad.dataset.adjust))}
