import{ supabase }from'./supabase.js';import{ requireBackoffice,setupShell,money,esc }from'./auth.js';
const $=x=>document.getElementById(x),ld=d=>{let x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`},pct=x=>`${Number(x||0).toFixed(2)}%`;
async function load(){ $('message').textContent='กำลังคำนวณ...';let{data:d,error}=await supabase.rpc('backoffice_pnl_v2',{p_date_from:$('dateFrom').value,p_date_to:$('dateTo').value});if(error){$('message').textContent=error.message;return}
$('rev').textContent=money(d.revenue);$('bills').textContent=`${d.bills} บิล`;$('cogs').textContent=money(d.theoretical_cogs);$('food').textContent=`Food Cost ${pct(d.theoretical_food_cost_pct)}`;$('gross').textContent=money(d.gross_profit);$('gm').textContent=`Margin ${pct(d.gross_margin_pct)}`;$('profit').textContent=money(d.operating_profit);$('pm').textContent=`Margin ${pct(d.operating_margin_pct)}`;
$('srev').textContent=money(d.revenue);$('scogs').textContent=`(${money(d.theoretical_cogs)})`;$('sgross').textContent=money(d.gross_profit);$('sexp').textContent=`(${money(d.operating_expenses)})`;$('sprofit').textContent=money(d.operating_profit);
$('expenses').innerHTML=(d.expense_breakdown||[]).map(x=>`<div class="row"><span style="padding-left:20px">${esc(x.category_name)}</span><span>(${money(x.amount)})</span></div>`).join('');
$('menuRows').innerHTML=(d.menu_analysis||[]).map(x=>`<tr><td>${esc(x.product_name)}</td><td class="num">${Number(x.quantity).toLocaleString('th-TH')}</td><td class="num">${money(x.revenue)}</td><td class="num">${money(x.cogs)}</td><td class="num">${pct(x.food_cost_pct)}</td><td class="num">${money(x.gross_profit)}</td></tr>`).join('');
$('stockInfo').innerHTML=d.actual_control_cogs==null?`<div class="warn"><b>ยังไม่ใช้ Actual COGS ในกำไรหลัก</b><br>ช่วงวันที่นี้ยังไม่มี Stock Closing ที่ปิดแล้วครบช่วง ระบบจึงใช้ Theoretical COGS จากยอดขาย/Recipe ก่อน เพื่อไม่เดาต้นทุนจริง</div>`:`<div class="good"><b>มีข้อมูล Stock Closing แล้ว</b><div class="row"><span>Actual Control COGS</span><b>${money(d.actual_control_cogs)}</b></div><div class="row"><span>Actual Food Cost</span><b>${pct(d.actual_food_cost_pct)}</b></div><div class="row"><span>Coverage การนับ Stock</span><b>${pct(d.stock_count_coverage_pct)}</b></div><div class="row total"><span>กำไรหลัง Actual Stock Cost</span><b>${money(d.actual_operating_profit)}</b></div></div>`;$('message').textContent=''}
function month(){let d=new Date();$('dateFrom').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`;$('dateTo').value=ld(d);load()}function today(){let d=ld(new Date());$('dateFrom').value=d;$('dateTo').value=d;load()}
$('load').onclick=load;$('month').onclick=month;$('today').onclick=today;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
let ctx=await requireBackoffice();if(ctx){setupShell(ctx,'pnl');month()}