import { supabase } from './supabase.js'
import { requireBackoffice, setupShell, esc } from './auth.js'
let products=[], ingredients=[], selected=null, rules={order_types:{dine_in:[],takeaway:[]},modifier_options:[]}
const $=id=>document.getElementById(id); const msg=t=>$('message').textContent=t||''
function ingOptions(id=''){return ingredients.map(i=>`<option value="${i.id}" ${i.id===id?'selected':''}>${esc(i.name)} (${esc(i.unit)})</option>`).join('')}
async function init(){const [p,i]=await Promise.all([supabase.rpc('backoffice_list_products'),supabase.rpc('backoffice_list_ingredients_v31')]);if(p.error)throw p.error;if(i.error)throw i.error;products=Array.isArray(p.data)?p.data:[];ingredients=(Array.isArray(i.data)?i.data:[]).filter(x=>x.is_active);$('productSelect').innerHTML='<option value="">-- เลือกสินค้า --</option>'+products.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
function recipeRow(r={},attrs=''){return `<div class="recipe-row"><label class="field"><span>วัตถุดิบ</span><select ${attrs} data-field="ingredient_id">${ingOptions(r.ingredient_id)}</select></label><label class="field"><span>จำนวน</span><input ${attrs} data-field="quantity_used" type="number" min="0.001" step="0.001" value="${Number(r.quantity_used||1)}"></label><button class="danger-btn" ${attrs} data-remove="1">ลบ</button></div>`}
function renderOrder(type){const rows=rules.order_types?.[type]||[];$(type==='dine_in'?'dineRows':'takeRows').innerHTML=rows.length?rows.map((r,i)=>recipeRow(r,`data-type="${type}" data-index="${i}"`)).join(''):'<div class="empty">ยังไม่มีรายการ</div>'}
function renderModifiers(){const c=$('modifierRules');const arr=rules.modifier_options||[];c.innerHTML=arr.length?arr.map((o,oi)=>`<article class="production-card" style="display:block"><div><strong>${esc(o.group_name)} → ${esc(o.option_name)}</strong><small>ราคาเพิ่ม ${Number(o.price_adjustment||0).toFixed(2)} บาท</small></div><div style="margin-top:10px" data-option-box="${o.option_id}">${(o.recipe||[]).length?(o.recipe||[]).map((r,i)=>recipeRow(r,`data-option-index="${oi}" data-index="${i}"`)).join(''):'<div class="empty">ยังไม่มีวัตถุดิบที่ตัดเพิ่ม</div>'}</div><div class="action-row" style="margin-top:10px"><button class="outline-btn" data-add-option="${oi}">＋ เพิ่มวัตถุดิบ</button><button class="primary-btn" data-save-option="${oi}">บันทึก Option นี้</button></div></article>`).join(''):'<div class="empty">เมนูนี้ยังไม่มี Modifier</div>'}
function render(){renderOrder('dine_in');renderOrder('takeaway');renderModifiers()}
async function load(id){selected=id; if(!id){$('workspace').classList.add('hidden');return} msg('กำลังโหลด...');const {data,error}=await supabase.rpc('backoffice_get_sale_stock_rules',{p_product_id:id});if(error){msg(error.message);return}rules=data||{order_types:{dine_in:[],takeaway:[]},modifier_options:[]};$('workspace').classList.remove('hidden');render();msg('')}
async function saveOrder(type){const recipe=(rules.order_types?.[type]||[]).filter(r=>r.ingredient_id&&Number(r.quantity_used)>0).map(r=>({ingredient_id:r.ingredient_id,quantity_used:Number(r.quantity_used)}));const {error}=await supabase.rpc('backoffice_save_order_type_stock_rule',{p_product_id:selected,p_order_type:type,p_recipe:recipe});if(error)return msg(error.message);msg('บันทึกสำเร็จ');await load(selected)}
async function saveOption(oi){const o=rules.modifier_options[oi];const recipe=(o.recipe||[]).filter(r=>r.ingredient_id&&Number(r.quantity_used)>0).map(r=>({ingredient_id:r.ingredient_id,quantity_used:Number(r.quantity_used)}));const {error}=await supabase.rpc('backoffice_save_modifier_stock_rule',{p_option_id:o.option_id,p_recipe:recipe});if(error)return msg(error.message);msg(`บันทึก ${o.option_name} สำเร็จ`);await load(selected)}
$('productSelect').onchange=e=>load(e.target.value)
$('workspace').onclick=e=>{const add=e.target.closest('[data-add]');if(add){const t=add.dataset.add;rules.order_types[t]=rules.order_types[t]||[];rules.order_types[t].push({ingredient_id:ingredients[0]?.id||'',quantity_used:1});renderOrder(t);return}const save=e.target.closest('[data-save]');if(save){saveOrder(save.dataset.save);return}const ao=e.target.closest('[data-add-option]');if(ao){const oi=+ao.dataset.addOption;rules.modifier_options[oi].recipe=rules.modifier_options[oi].recipe||[];rules.modifier_options[oi].recipe.push({ingredient_id:ingredients[0]?.id||'',quantity_used:1});renderModifiers();return}const so=e.target.closest('[data-save-option]');if(so){saveOption(+so.dataset.saveOption);return}const rm=e.target.closest('[data-remove]');if(rm){const i=+rm.dataset.index;if(rm.dataset.type){rules.order_types[rm.dataset.type].splice(i,1);renderOrder(rm.dataset.type)}else if(rm.dataset.optionIndex!==undefined){const oi=+rm.dataset.optionIndex;rules.modifier_options[oi].recipe.splice(i,1);renderModifiers()}}}
$('workspace').oninput=e=>{const f=e.target.dataset.field;if(!f)return;const i=+e.target.dataset.index;const val=f==='quantity_used'?Number(e.target.value||0):e.target.value;if(e.target.dataset.type){rules.order_types[e.target.dataset.type][i][f]=val}else if(e.target.dataset.optionIndex!==undefined){rules.modifier_options[+e.target.dataset.optionIndex].recipe[i][f]=val}}
$('workspace').onchange=$('workspace').oninput
const ctx=await requireBackoffice();if(ctx){setupShell(ctx,'sale-rules');try{await init()}catch(e){msg(e.message)}}
