import { supabase } from './supabase.js'
import { requireBackoffice, setupShell, money, number, esc } from './auth.js'
let rows=[],current=null
const ctx=await requireBackoffice();if(ctx){setupShell(ctx,'count');await load()}
async function load(){const{data,error}=await supabase.rpc('backoffice_list_stock_counts');if(error)return msg(error.message);rows=data||[];render()}
function msg(t=''){document.getElementById('message').textContent=t}
function render(){document.getElementById('list').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>เลขที่</th><th>วันที่</th><th>สถานะ</th><th class="num">มูลค่าคลาดเคลื่อน</th><th>ผู้สร้าง</th><th>จัดการ</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.count_no)}</strong></td><td>${new Date(x.created_at).toLocaleString('th-TH')}</td><td><span class="status-pill ${x.status}">${x.status==='counting'?'กำลังนับ':x.status==='completed'?'เสร็จแล้ว':x.status}</span></td><td class="num">${money(x.variance_value)}</td><td>${esc(x.created_by_name||'-')}</td><td><button class="small-btn" data-open="${x.id}">${x.status==='counting'?'กรอกการนับ':'ดูผล'}</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">ยังไม่มี Stock Count</div>'}
async function create(){const note=prompt('หมายเหตุการนับ (ถ้ามี)','ตรวจนับประจำวัน');if(note===null)return;const{data,error}=await supabase.rpc('backoffice_create_stock_count',{p_note:note||null});if(error)return msg(error.message);await load();await openCount(data)}
async function openCount(id){const{data,error}=await supabase.rpc('backoffice_get_stock_count',{p_stock_count_id:id});if(error)return msg(error.message);current=data;document.getElementById('countTitle').textContent=`${data.count_no} • ${data.status==='counting'?'กำลังนับ':'เสร็จแล้ว'}`;const editable=data.status==='counting';document.getElementById('countItems').innerHTML=`<div class="table-wrap"><table><thead><tr><th>วัตถุดิบ</th><th class="num">ระบบ</th><th class="num">นับจริง</th><th class="num">ต่าง</th><th class="num">มูลค่าต่าง</th></tr></thead><tbody>${(data.items||[]).map(x=>{const c=x.counted_qty===null?'':x.counted_qty,v=x.counted_qty===null?0:Number(x.counted_qty)-Number(x.system_qty),vv=v*Number(x.unit_cost);return`<tr><td><strong>${esc(x.ingredient_name)}</strong><br><small>${esc(x.unit)}</small></td><td class="num">${number(x.system_qty)}</td><td class="num">${editable?`<input class="table-input" data-count="${x.id}" type="number" min="0" step="0.001" value="${c}">`:number(x.counted_qty)}</td><td class="num ${v>0?'variance-plus':v<0?'variance-minus':''}" data-var="${x.id}">${number(v)}</td><td class="num" data-var-value="${x.id}">${money(vv)}</td></tr>`}).join('')}</tbody></table></div>`;document.getElementById('saveCountBtn').classList.toggle('hidden',!editable);document.getElementById('completeCountBtn').classList.toggle('hidden',!editable);document.getElementById('countMessage').textContent='';document.getElementById('countModal').classList.remove('hidden')}
function itemsPayload(){return [...document.querySelectorAll('[data-count]')].map(i=>({item_id:i.dataset.count,counted_qty:i.value===''?null:Number(i.value)}))}
async function save(){const items=itemsPayload();if(items.some(x=>x.counted_qty===null||x.counted_qty<0))return cmsg('กรุณากรอกจำนวนที่นับจริงให้ครบ');const{error}=await supabase.rpc('backoffice_save_stock_count_items',{p_stock_count_id:current.id,p_items:items});if(error)return cmsg(error.message);cmsg('บันทึกการนับแล้ว');await openCount(current.id)}
async function complete(){if(!confirm('ยืนยันปิด Stock Count? ระบบจะปรับยอด Stock ตามจำนวนที่นับจริง'))return;await save();if(document.getElementById('countMessage').textContent.includes('กรุณา'))return;const{data,error}=await supabase.rpc('backoffice_complete_stock_count',{p_stock_count_id:current.id});if(error)return cmsg(error.message.includes('STOCK_COUNT_INCOMPLETE')?'ยังกรอกจำนวนไม่ครบ':error.message);document.getElementById('countModal').classList.add('hidden');msg(`ปิดการนับสำเร็จ ปรับ Stock ${data?.movement_count||0} รายการ`);await load()}
function cmsg(t){document.getElementById('countMessage').textContent=t}
document.getElementById('newBtn').onclick=create;document.getElementById('closeCount').onclick=()=>document.getElementById('countModal').classList.add('hidden');document.getElementById('saveCountBtn').onclick=save;document.getElementById('completeCountBtn').onclick=complete;document.getElementById('list').onclick=e=>{const b=e.target.closest('[data-open]');if(b)openCount(b.dataset.open)}
document.getElementById('countItems').oninput=e=>{const i=e.target.closest('[data-count]');if(!i)return;const item=current.items.find(x=>x.id===i.dataset.count),v=Number(i.value||0)-Number(item.system_qty||0),vv=v*Number(item.unit_cost||0);const ve=document.querySelector(`[data-var="${i.dataset.count}"]`),vve=document.querySelector(`[data-var-value="${i.dataset.count}"]`);ve.textContent=number(v);ve.className=`num ${v>0?'variance-plus':v<0?'variance-minus':''}`;vve.textContent=money(vv)}
