import{ supabase }from'./supabase.js';import{requireBackoffice,setupShell,money,number,esc}from'./auth.js'
let rows=[],cats=[];const ctx=await requireBackoffice();if(ctx){setupShell(ctx,'reports');setMonth();await loadCats();await load()}
function isoDate(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function setMonth(){const n=new Date();document.getElementById('from').value=isoDate(new Date(n.getFullYear(),n.getMonth(),1));document.getElementById('to').value=isoDate(n)}
async function loadCats(){const{data}=await supabase.rpc('backoffice_list_ingredient_categories');cats=data||[];document.getElementById('category').innerHTML='<option value="">ทุกหมวด</option>'+cats.filter(x=>x.is_active).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
function bounds(){return{from:new Date(`${document.getElementById('from').value}T00:00:00`).toISOString(),to:new Date(`${document.getElementById('to').value}T23:59:59.999`).toISOString()}}
async function load(){const b=bounds();const{data,error}=await supabase.rpc('backoffice_stock_report_v3',{p_from:b.from,p_to:b.to,p_category_id:document.getElementById('category').value||null});if(error){document.getElementById('message').textContent=error.message;return}rows=data||[];document.getElementById('message').textContent='';render()}
const sum=k=>rows.reduce((s,x)=>s+Number(x[k]||0),0)
function render(){document.getElementById('stockValue').textContent=money(sum('stock_value'));document.getElementById('inValue').textContent=money(sum('stock_in_value'));document.getElementById('saleValue').textContent=money(sum('sale_value'));document.getElementById('wasteValue').textContent=money(sum('waste_value'));document.getElementById('adjInValue').textContent=money(sum('adjust_in_value'));document.getElementById('adjOutValue').textContent=money(sum('adjust_out_value'));renderCats();renderTable()}
function renderCats(){const m=new Map();for(const x of rows){const k=x.category_name||'อื่นๆ',o=m.get(k)||{stock:0,sale:0,waste:0,inn:0};o.stock+=Number(x.stock_value||0);o.sale+=Number(x.sale_value||0);o.waste+=Number(x.waste_value||0);o.inn+=Number(x.stock_in_value||0);m.set(k,o)}document.getElementById('categorySummary').innerHTML=[...m].map(([k,o])=>`<article class="category-cost-card"><h4>${esc(k)}</h4><div class="category-cost-row"><span>Stock ปัจจุบัน</span><strong>${money(o.stock)}</strong></div><div class="category-cost-row"><span>รับเข้า</span><strong>${money(o.inn)}</strong></div><div class="category-cost-row"><span>ใช้จากขาย</span><strong>${money(o.sale)}</strong></div><div class="category-cost-row"><span>ของเสีย</span><strong class="${o.waste>0?'loss':''}">${money(o.waste)}</strong></div></article>`).join('')}
function renderTable(){const q=document.getElementById('search').value.trim().toLowerCase(),list=rows.filter(x=>!q||`${x.name} ${x.category_name}`.toLowerCase().includes(q));document.getElementById('table').innerHTML=list.length?`<div class="table-wrap"><table class="raw-table"><thead><tr><th>วัตถุดิบ</th><th>หมวด</th><th>รอบนับ</th><th class="num">คงเหลือ</th><th class="num">มูลค่า Stock</th><th class="num">รับเข้า Qty</th><th class="num">รับเข้า ฿</th><th class="num">ขายใช้ Qty</th><th class="num">ขายใช้ ฿</th><th class="num">เสีย Qty</th><th class="num">เสีย ฿</th><th class="num">ปรับ+ Qty</th><th class="num">ปรับ+ ฿</th><th class="num">ปรับ- Qty</th><th class="num">ปรับ- ฿</th><th class="num">คืน Qty</th><th>สถานะ</th></tr></thead><tbody>${list.map(x=>`<tr><td><strong>${esc(x.name)}</strong><br><small>${esc(x.unit)}</small></td><td>${esc(x.category_name)}</td><td>${x.count_frequency}</td><td class="num">${number(x.current_stock)}</td><td class="num">${money(x.stock_value)}</td><td class="num">${number(x.stock_in_qty)}</td><td class="num">${money(x.stock_in_value)}</td><td class="num">${number(x.sale_qty)}</td><td class="num">${money(x.sale_value)}</td><td class="num">${number(x.waste_qty)}</td><td class="num loss">${money(x.waste_value)}</td><td class="num">${number(x.adjust_in_qty)}</td><td class="num">${money(x.adjust_in_value)}</td><td class="num">${number(x.adjust_out_qty)}</td><td class="num">${money(x.adjust_out_value)}</td><td class="num">${number(x.void_qty)}</td><td>${x.status==='ok'?'ปกติ':x.status==='low'?'ใกล้หมด':x.status==='out'?'หมด':'ปิด'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">ไม่พบข้อมูล</div>'}
document.getElementById('applyBtn').onclick=load;document.getElementById('refreshBtn').onclick=load;document.getElementById('search').oninput=renderTable
