import{ supabase }from'./supabase.js';import{requireBackoffice,setupShell,money,number,esc}from'./auth.js'
let rows=[],current=null;
function typeText(x){return({daily:'รายวัน',weekly:'รายสัปดาห์',monthly:'รายเดือน',full:'Full Count'})[x]||x}
async function load(){const{data,error}=await supabase.rpc('backoffice_list_stock_counts_v3');if(error)return msg(error.message);rows=data||[];render()}
function msg(t=''){document.getElementById('message').textContent=t}
function render(){document.getElementById('list').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>เลขที่</th><th>รอบ</th><th>วันที่</th><th>สถานะ</th><th class="num">จำนวนรายการ</th><th class="num">มูลค่าคลาดเคลื่อน</th><th>จัดการ</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.count_no)}</strong></td><td>${typeText(x.count_type)}</td><td>${new Date(x.created_at).toLocaleString('th-TH')}</td><td><span class="status-pill ${x.status}">${x.status==='counting'?'กำลังนับ':x.status==='completed'?'เสร็จแล้ว':x.status}</span></td><td class="num">${number(x.item_count,0)}</td><td class="num">${money(x.variance_value)}</td><td><button class="small-btn" data-open="${x.id}">${x.status==='counting'?'กรอกการนับ':'ดูผล'}</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">ยังไม่มี Stock Count</div>'}
async function create(){const{data,error}=await supabase.rpc('backoffice_create_stock_count_v3',{p_count_type:document.getElementById('countType').value,p_note:document.getElementById('newNote').value||null});if(error){document.getElementById('newMessage').textContent=error.message;return}document.getElementById('newModal').classList.add('hidden');await load();await openCount(data)}
async function openCount(id){const{data,error}=await supabase.rpc('backoffice_get_stock_count_v3',{p_stock_count_id:id});if(error)return msg(error.message);current=data;document.getElementById('countTitle').textContent=data.count_no;document.getElementById('countSub').textContent=`${typeText(data.count_type)} • ${data.items.length} รายการ`;const editable=data.status==='counting';document.getElementById('countItems').innerHTML=`<div class="table-wrap"><table><thead><tr><th>หมวด</th><th>วัตถุดิบ</th><th>รอบ</th><th class="num">ระบบ</th><th class="num">นับจริง</th><th class="num">ต่าง</th><th class="num">มูลค่าต่าง</th></tr></thead><tbody>${data.items.map(x=>{const c=x.counted_qty===null?'':x.counted_qty,v=x.counted_qty===null?0:Number(x.counted_qty)-Number(x.system_qty),vv=v*Number(x.unit_cost);return`<tr><td><span class="category-chip">${esc(x.category_name)}</span></td><td><strong>${esc(x.ingredient_name)}</strong><br><small>${esc(x.unit)}</small></td><td>${typeText(x.count_frequency)}</td><td class="num">${number(x.system_qty)}</td><td class="num">${editable?`<input class="table-input" data-count="${x.id}" type="number" min="0" step="0.001" value="${c}">`:number(x.counted_qty)}</td><td class="num ${v<0?'loss':v>0?'gain':''}" data-var="${x.id}">${number(v)}</td><td class="num" data-vv="${x.id}">${money(vv)}</td></tr>`}).join('')}</tbody></table></div>`;document.getElementById('saveCountBtn').classList.toggle('hidden',!editable);document.getElementById('completeCountBtn').classList.toggle('hidden',!editable);document.getElementById('countMessage').textContent='';document.getElementById('countModal').classList.remove('hidden')}
function payload(){return[...document.querySelectorAll('[data-count]')].map(i=>({item_id:i.dataset.count,counted_qty:i.value===''?null:Number(i.value)}))}
async function save(show='บันทึกการนับแล้ว'){const a=payload();if(a.some(x=>x.counted_qty===null||x.counted_qty<0)){cmsg('กรุณากรอกจำนวนที่นับจริงให้ครบ');return false}const{error}=await supabase.rpc('backoffice_save_stock_count_items',{p_stock_count_id:current.id,p_items:a});if(error){cmsg(error.message);return false}cmsg(show);return true}
async function complete(){if(!confirm('ยืนยันปิด Stock Count? ระบบจะปรับยอด Stock ตามจำนวนที่นับจริง'))return;if(!await save(''))return;const{data,error}=await supabase.rpc('backoffice_complete_stock_count',{p_stock_count_id:current.id});if(error)return cmsg(error.message);document.getElementById('countModal').classList.add('hidden');msg(`สำเร็จ • ปรับ Stock ${data?.movement_count||0} รายการ • มูลค่าคลาดเคลื่อน ${money(data?.variance_value||0)}`);await load()}
function cmsg(t){document.getElementById('countMessage').textContent=t}
document.getElementById('newBtn').onclick=()=>{document.getElementById('newNote').value='';document.getElementById('newMessage').textContent='';document.getElementById('newModal').classList.remove('hidden')};document.getElementById('closeNew').onclick=()=>document.getElementById('newModal').classList.add('hidden');document.getElementById('createBtn').onclick=create;document.getElementById('closeCount').onclick=()=>document.getElementById('countModal').classList.add('hidden');document.getElementById('saveCountBtn').onclick=()=>save();document.getElementById('completeCountBtn').onclick=complete;document.getElementById('list').onclick=e=>{const b=e.target.closest('[data-open]');if(b)openCount(b.dataset.open)};document.getElementById('countItems').oninput=e=>{const i=e.target.closest('[data-count]');if(!i)return;const x=current.items.find(z=>z.id===i.dataset.count),v=Number(i.value||0)-Number(x.system_qty||0);document.querySelector(`[data-var="${i.dataset.count}"]`).textContent=number(v);document.querySelector(`[data-vv="${i.dataset.count}"]`).textContent=money(v*Number(x.unit_cost||0))}

const ctx=await requireBackoffice();if(ctx){setupShell(ctx,'count');await load()}
