import { supabase } from './supabase.js'
import { requireBackoffice, setupShell, esc } from './auth.js'
let rows=[]
const ctx=await requireBackoffice();if(ctx){setupShell(ctx,'suppliers');await load()}
async function load(){const{data,error}=await supabase.rpc('backoffice_list_suppliers');if(error)return msg(error.message);rows=Array.isArray(data)?data:[];render()}
function msg(t=''){document.getElementById('message').textContent=t}
function render(){const q=document.getElementById('search').value.trim().toLowerCase(),s=document.getElementById('status').value,list=rows.filter(x=>(!q||`${x.name} ${x.contact_name||''} ${x.phone||''}`.toLowerCase().includes(q))&&(!s||(s==='active'?x.is_active:!x.is_active)));document.getElementById('table').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Supplier</th><th>ผู้ติดต่อ</th><th>โทร</th><th>เงื่อนไข</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>${list.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.contact_name||'-')}</td><td>${esc(x.phone||'-')}</td><td>${esc(x.payment_terms||'-')}</td><td><span class="badge ${x.is_active?'ok':''}">${x.is_active?'ใช้งาน':'ปิด'}</span></td><td><button class="small-btn" data-edit="${x.id}">แก้ไข</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">ยังไม่มี Supplier</div>'}
function open(r=null){document.getElementById('supplierId').value=r?.id||'';for(const [id,k] of [['name','name'],['contactName','contact_name'],['phone','phone'],['email','email'],['taxId','tax_id'],['paymentTerms','payment_terms'],['address','address'],['note','note']])document.getElementById(id).value=r?.[k]||'';document.getElementById('active').checked=r?r.is_active!==false:true;document.getElementById('formMessage').textContent='';document.getElementById('modal').classList.remove('hidden')}
async function save(){const name=document.getElementById('name').value.trim();if(!name)return formMsg('กรุณาระบุชื่อ Supplier');const{error}=await supabase.rpc('backoffice_save_supplier',{p_supplier_id:document.getElementById('supplierId').value||null,p_name:name,p_contact_name:document.getElementById('contactName').value||null,p_phone:document.getElementById('phone').value||null,p_email:document.getElementById('email').value||null,p_tax_id:document.getElementById('taxId').value||null,p_address:document.getElementById('address').value||null,p_payment_terms:document.getElementById('paymentTerms').value||null,p_note:document.getElementById('note').value||null,p_is_active:document.getElementById('active').checked});if(error)return formMsg(error.message.includes('SUPPLIER_NAME_EXISTS')?'มี Supplier ชื่อนี้แล้ว':error.message);document.getElementById('modal').classList.add('hidden');await load()}
function formMsg(t){document.getElementById('formMessage').textContent=t}
document.getElementById('addBtn').onclick=()=>open();document.getElementById('closeBtn').onclick=()=>document.getElementById('modal').classList.add('hidden');document.getElementById('saveBtn').onclick=save;document.getElementById('search').oninput=render;document.getElementById('status').onchange=render;document.getElementById('table').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)open(rows.find(x=>x.id===b.dataset.edit))}
